### ISSUE TITLE
Project does not follow semantic versioning. 

### ISSUE THREAD

**Issue by AutomatedTester** [slog-rs/stream#1]
The Changelog has numerous breaking changes between minor number changes. According to Semver, these breaking changes can't happen unless this is a major version change.

I have just upgraded to 1.2 and my project doesnt compile because of one of these breaking changes.

**Comment by AutomatedTester** [comment]
compile error

```
error[E0432]: unresolved import `slog_stream::AsyncStreamer`. There is no `AsyncStreamer` in `slog_stream`
  --> src/logging.rs:11:27
   |
11 | use slog_stream::{Format, AsyncStreamer};
   |                           ^^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `geckodriver`.

To learn more, run the command again with --verbose.
```

**Comment by dpc** [comment]
Yes. Sorry for that. I did couple of breaking changes here and there for stuff that turned out wrong, since I assumed it's still early and not many people are using APIs that I broke. I understand that I'm at fault here, and you have all the rights to complain. On the bright side: I think it won't happen again. :)

This particular break was due to the `Async` becoming it's own `Drain`, instead of being coupled in `AsyncStremer`. Feel free to ping my on gitter if you have any troubles fixing your code, and again... sorry for that.
